export type RaceHeroTheme = {
  key: string;
  aliases: string[];
  primary: string;
  secondary: string;
  glow: string;
  accentSoft: string;
  circuitId: string;
  layoutId: string;
  svgStyle: "white-outline";
  overlayWidth: string;
  overlayOpacity: number;
  overlayOffsetX: string;
  overlayOffsetY: string;
  overlayScale?: number;
};

export type RaceHeroPreviewOption = {
  key: string;
  label: string;
  raceName: string;
  round: number;
};

const DEFAULT_THEME: RaceHeroTheme = {
  key: "default",
  aliases: [],
  primary: "#111216",
  secondary: "#20232b",
  glow: "rgba(204, 0, 0, 0.22)",
  accentSoft: "rgba(255, 255, 255, 0.035)",
  circuitId: "",
  layoutId: "",
  svgStyle: "white-outline",
  overlayWidth: "80%",
  overlayOpacity: 0.12,
  overlayOffsetX: "0%",
  overlayOffsetY: "0%",
  overlayScale: 1,
};

const THEMES: RaceHeroTheme[] = [
  {
    key: "melbourne",
    aliases: ["australian grand prix", "melbourne"],
    primary: "#10253d",
    secondary: "#1e4f73",
    glow: "rgba(225, 6, 0, 0.24)",
    accentSoft: "rgba(145, 205, 255, 0.08)",
    circuitId: "melbourne",
    layoutId: "melbourne-2",
    svgStyle: "white-outline",
    overlayWidth: "84%",
    overlayOpacity: 0.13,
    overlayOffsetX: "0%",
    overlayOffsetY: "4%",
  },
  {
    key: "shanghai",
    aliases: ["chinese grand prix", "shanghai"],
    primary: "#2a1112",
    secondary: "#5b1a1e",
    glow: "rgba(232, 170, 70, 0.2)",
    accentSoft: "rgba(255, 219, 122, 0.08)",
    circuitId: "shanghai",
    layoutId: "shanghai-1",
    svgStyle: "white-outline",
    overlayWidth: "82%",
    overlayOpacity: 0.12,
    overlayOffsetX: "2%",
    overlayOffsetY: "3%",
  },
  {
    key: "suzuka",
    aliases: ["japanese grand prix", "suzuka"],
    primary: "#1d1718",
    secondary: "#5a2427",
    glow: "rgba(239, 68, 68, 0.2)",
    accentSoft: "rgba(255, 245, 214, 0.08)",
    circuitId: "suzuka",
    layoutId: "suzuka-2",
    svgStyle: "white-outline",
    overlayWidth: "74%",
    overlayOpacity: 0.13,
    overlayOffsetX: "8%",
    overlayOffsetY: "2%",
  },
  {
    key: "miami",
    aliases: ["miami grand prix", "miami"],
    primary: "#0f2c33",
    secondary: "#14808f",
    glow: "rgba(255, 112, 67, 0.22)",
    accentSoft: "rgba(101, 232, 255, 0.1)",
    circuitId: "miami",
    layoutId: "miami-1",
    svgStyle: "white-outline",
    overlayWidth: "100%",
    overlayOpacity: 0.14,
    overlayOffsetX: "0%",
    overlayOffsetY: "0%",
    overlayScale: 2.00,
  },
  {
    key: "imola",
    aliases: ["emilia-romagna grand prix", "emilia romagna grand prix", "imola"],
    primary: "#16201b",
    secondary: "#315141",
    glow: "rgba(225, 6, 0, 0.18)",
    accentSoft: "rgba(159, 255, 196, 0.06)",
    circuitId: "imola",
    layoutId: "imola-3",
    svgStyle: "white-outline",
    overlayWidth: "100%",
    overlayOpacity: 0.14,
    overlayOffsetX: "0%",
    overlayOffsetY: "0%",
    overlayScale: 2.00,
  },
  {
    key: "monaco",
    aliases: ["monaco grand prix", "monaco"],
    primary: "#1b1618",
    secondary: "#3b2c31",
    glow: "rgba(212, 175, 55, 0.18)",
    accentSoft: "rgba(255, 245, 214, 0.08)",
    circuitId: "monaco",
    layoutId: "monaco-6",
    svgStyle: "white-outline",
    overlayWidth: "72%",
    overlayOpacity: 0.13,
    overlayOffsetX: "3%",
    overlayOffsetY: "1%",
  },
  {
    key: "spain",
    aliases: ["spanish grand prix", "spain grand prix", "barcelona", "catalunya"],
    primary: "#2c1520",
    secondary: "#6e2337",
    glow: "rgba(255, 191, 71, 0.16)",
    accentSoft: "rgba(255, 203, 112, 0.06)",
    circuitId: "catalunya",
    layoutId: "catalunya-6",
    svgStyle: "white-outline",
    overlayWidth: "80%",
    overlayOpacity: 0.12,
    overlayOffsetX: "1%",
    overlayOffsetY: "2%",
  },
  {
    key: "canada",
    aliases: ["canadian grand prix", "canada grand prix", "montreal", "gilles villeneuve"],
    primary: "#162432",
    secondary: "#2b5d87",
    glow: "rgba(225, 6, 0, 0.18)",
    accentSoft: "rgba(187, 223, 255, 0.06)",
    circuitId: "montreal",
    layoutId: "montreal-6",
    svgStyle: "white-outline",
    overlayWidth: "82%",
    overlayOpacity: 0.12,
    overlayOffsetX: "1%",
    overlayOffsetY: "3%",
  },
  {
    key: "austria",
    aliases: ["austrian grand prix", "austria grand prix", "red bull ring", "spielberg"],
    primary: "#171a24",
    secondary: "#2c3758",
    glow: "rgba(225, 6, 0, 0.2)",
    accentSoft: "rgba(186, 204, 255, 0.06)",
    circuitId: "spielberg",
    layoutId: "spielberg-3",
    svgStyle: "white-outline",
    overlayWidth: "80%",
    overlayOpacity: 0.12,
    overlayOffsetX: "2%",
    overlayOffsetY: "2%",
  },
  {
    key: "silverstone",
    aliases: ["british grand prix", "silverstone"],
    primary: "#0f1d34",
    secondary: "#244e88",
    glow: "rgba(225, 6, 0, 0.2)",
    accentSoft: "rgba(117, 180, 255, 0.08)",
    circuitId: "silverstone",
    layoutId: "silverstone-8",
    svgStyle: "white-outline",
    overlayWidth: "84%",
    overlayOpacity: 0.13,
    overlayOffsetX: "2%",
    overlayOffsetY: "1%",
  },
  {
    key: "belgium",
    aliases: ["belgian grand prix", "belgium grand prix", "spa", "spa-francorchamps"],
    primary: "#1a1b29",
    secondary: "#394879",
    glow: "rgba(225, 6, 0, 0.16)",
    accentSoft: "rgba(149, 171, 255, 0.06)",
    circuitId: "spa-francorchamps",
    layoutId: "spa-francorchamps-4",
    svgStyle: "white-outline",
    overlayWidth: "79%",
    overlayOpacity: 0.12,
    overlayOffsetX: "3%",
    overlayOffsetY: "2%",
  },
  {
    key: "hungary",
    aliases: ["hungarian grand prix", "hungary grand prix", "hungaroring"],
    primary: "#23161a",
    secondary: "#5f2a34",
    glow: "rgba(239, 68, 68, 0.16)",
    accentSoft: "rgba(255, 191, 191, 0.06)",
    circuitId: "hungaroring",
    layoutId: "hungaroring-3",
    svgStyle: "white-outline",
    overlayWidth: "76%",
    overlayOpacity: 0.12,
    overlayOffsetX: "4%",
    overlayOffsetY: "2%",
  },
  {
    key: "netherlands",
    aliases: ["dutch grand prix", "netherlands grand prix", "zandvoort"],
    primary: "#1f1b15",
    secondary: "#624123",
    glow: "rgba(255, 122, 0, 0.18)",
    accentSoft: "rgba(255, 203, 145, 0.06)",
    circuitId: "zandvoort",
    layoutId: "zandvoort-5",
    svgStyle: "white-outline",
    overlayWidth: "80%",
    overlayOpacity: 0.12,
    overlayOffsetX: "2%",
    overlayOffsetY: "3%",
  },
  {
    key: "monza",
    aliases: ["italian grand prix", "monza"],
    primary: "#162219",
    secondary: "#25533a",
    glow: "rgba(225, 6, 0, 0.22)",
    accentSoft: "rgba(141, 255, 184, 0.08)",
    circuitId: "monza",
    layoutId: "monza-7",
    svgStyle: "white-outline",
    overlayWidth: "76%",
    overlayOpacity: 0.13,
    overlayOffsetX: "1%",
    overlayOffsetY: "4%",
  },
  {
    key: "azerbaijan",
    aliases: ["azerbaijan grand prix", "azerbaijan", "baku"],
    primary: "#13212a",
    secondary: "#255f73",
    glow: "rgba(89, 217, 255, 0.12)",
    accentSoft: "rgba(119, 241, 255, 0.06)",
    circuitId: "baku",
    layoutId: "baku-1",
    svgStyle: "white-outline",
    overlayWidth: "77%",
    overlayOpacity: 0.12,
    overlayOffsetX: "4%",
    overlayOffsetY: "1%",
  },
  {
    key: "singapore",
    aliases: ["singapore grand prix", "singapore", "marina bay"],
    primary: "#241530",
    secondary: "#50306b",
    glow: "rgba(0, 212, 255, 0.14)",
    accentSoft: "rgba(255, 94, 247, 0.08)",
    circuitId: "marina-bay",
    layoutId: "marina-bay-4",
    svgStyle: "white-outline",
    overlayWidth: "74%",
    overlayOpacity: 0.13,
    overlayOffsetX: "3%",
    overlayOffsetY: "3%",
  },
  {
    key: "usa",
    aliases: ["united states grand prix", "united states", "usa grand prix", "austin", "cota", "circuit of the americas"],
    primary: "#1b1d28",
    secondary: "#33466e",
    glow: "rgba(225, 6, 0, 0.18)",
    accentSoft: "rgba(145, 182, 255, 0.06)",
    circuitId: "austin",
    layoutId: "austin-1",
    svgStyle: "white-outline",
    overlayWidth: "78%",
    overlayOpacity: 0.12,
    overlayOffsetX: "2%",
    overlayOffsetY: "3%",
  },
  {
    key: "mexico-city",
    aliases: ["mexico city grand prix", "mexican grand prix", "mexico city", "mexico", "hermanos rodriguez"],
    primary: "#1d1a14",
    secondary: "#4e4726",
    glow: "rgba(225, 6, 0, 0.15)",
    accentSoft: "rgba(201, 255, 163, 0.05)",
    circuitId: "mexico-city",
    layoutId: "mexico-city-3",
    svgStyle: "white-outline",
    overlayWidth: "82%",
    overlayOpacity: 0.12,
    overlayOffsetX: "1%",
    overlayOffsetY: "3%",
  },
  {
    key: "sao-paulo",
    aliases: ["sao paulo grand prix", "são paulo grand prix", "brazilian grand prix", "brazil", "interlagos"],
    primary: "#162118",
    secondary: "#28522c",
    glow: "rgba(234, 179, 8, 0.14)",
    accentSoft: "rgba(194, 255, 118, 0.06)",
    circuitId: "interlagos",
    layoutId: "interlagos-2",
    svgStyle: "white-outline",
    overlayWidth: "80%",
    overlayOpacity: 0.12,
    overlayOffsetX: "3%",
    overlayOffsetY: "2%",
  },
  {
    key: "las-vegas",
    aliases: ["las vegas grand prix", "las vegas"],
    primary: "#23111f",
    secondary: "#5b1f51",
    glow: "rgba(255, 185, 0, 0.18)",
    accentSoft: "rgba(255, 78, 205, 0.08)",
    circuitId: "las-vegas",
    layoutId: "las-vegas-1",
    svgStyle: "white-outline",
    overlayWidth: "88%",
    overlayOpacity: 0.14,
    overlayOffsetX: "1%",
    overlayOffsetY: "4%",
  },
  {
    key: "qatar",
    aliases: ["qatar grand prix", "qatar", "losail", "lusail"],
    primary: "#1d1a26",
    secondary: "#4b3f7d",
    glow: "rgba(112, 82, 255, 0.16)",
    accentSoft: "rgba(198, 172, 255, 0.06)",
    circuitId: "lusail",
    layoutId: "lusail-1",
    svgStyle: "white-outline",
    overlayWidth: "80%",
    overlayOpacity: 0.12,
    overlayOffsetX: "2%",
    overlayOffsetY: "3%",
  },
  {
    key: "abu-dhabi",
    aliases: ["abu dhabi grand prix", "abu dhabi", "yas marina"],
    primary: "#14232c",
    secondary: "#1e5763",
    glow: "rgba(234, 179, 8, 0.16)",
    accentSoft: "rgba(137, 223, 255, 0.08)",
    circuitId: "yas-marina",
    layoutId: "yas-marina-2",
    svgStyle: "white-outline",
    overlayWidth: "76%",
    overlayOpacity: 0.12,
    overlayOffsetX: "4%",
    overlayOffsetY: "1%",
  },
  {
    key: "saudi-arabia",
    aliases: ["saudi arabian grand prix", "saudi arabia grand prix", "saudi arabia", "jeddah"],
    primary: "#13211d",
    secondary: "#1d5a47",
    glow: "rgba(49, 214, 126, 0.12)",
    accentSoft: "rgba(149, 255, 206, 0.05)",
    circuitId: "jeddah",
    layoutId: "jeddah-1",
    svgStyle: "white-outline",
    overlayWidth: "86%",
    overlayOpacity: 0.12,
    overlayOffsetX: "3%",
    overlayOffsetY: "2%",
  },
  {
    key: "bahrain",
    aliases: ["bahrain grand prix", "bahrain", "sakhir"],
    primary: "#241b17",
    secondary: "#6a4230",
    glow: "rgba(245, 158, 11, 0.14)",
    accentSoft: "rgba(255, 215, 163, 0.06)",
    circuitId: "bahrain",
    layoutId: "bahrain-1",
    svgStyle: "white-outline",
    overlayWidth: "80%",
    overlayOpacity: 0.12,
    overlayOffsetX: "2%",
    overlayOffsetY: "3%",
  },
];

export const RACE_HERO_PREVIEW_OPTIONS: RaceHeroPreviewOption[] = [
  { key: "australia", label: "Round 1 · Australian Grand Prix", raceName: "Australian Grand Prix", round: 1 },
  { key: "china", label: "Round 2 · Chinese Grand Prix", raceName: "Chinese Grand Prix", round: 2 },
  { key: "japan", label: "Round 3 · Japanese Grand Prix", raceName: "Japanese Grand Prix", round: 3 },
  { key: "bahrain", label: "Round 4 · Bahrain Grand Prix", raceName: "Bahrain Grand Prix", round: 4 },
  { key: "saudi-arabia", label: "Round 5 · Saudi Arabian Grand Prix", raceName: "Saudi Arabian Grand Prix", round: 5 },
  { key: "miami", label: "Round 6 · Miami Grand Prix", raceName: "Miami Grand Prix", round: 6 },
  { key: "imola", label: "Round 7 · Emilia-Romagna Grand Prix", raceName: "Emilia-Romagna Grand Prix", round: 7 },
  { key: "monaco", label: "Round 8 · Monaco Grand Prix", raceName: "Monaco Grand Prix", round: 8 },
  { key: "spain", label: "Round 9 · Spanish Grand Prix", raceName: "Spanish Grand Prix", round: 9 },
  { key: "canada", label: "Round 10 · Canadian Grand Prix", raceName: "Canadian Grand Prix", round: 10 },
  { key: "austria", label: "Round 11 · Austrian Grand Prix", raceName: "Austrian Grand Prix", round: 11 },
  { key: "silverstone", label: "Round 12 · British Grand Prix", raceName: "British Grand Prix", round: 12 },
  { key: "belgium", label: "Round 13 · Belgian Grand Prix", raceName: "Belgian Grand Prix", round: 13 },
  { key: "hungary", label: "Round 14 · Hungarian Grand Prix", raceName: "Hungarian Grand Prix", round: 14 },
  { key: "netherlands", label: "Round 15 · Dutch Grand Prix", raceName: "Dutch Grand Prix", round: 15 },
  { key: "monza", label: "Round 16 · Italian Grand Prix", raceName: "Italian Grand Prix", round: 16 },
  { key: "azerbaijan", label: "Round 17 · Azerbaijan Grand Prix", raceName: "Azerbaijan Grand Prix", round: 17 },
  { key: "singapore", label: "Round 18 · Singapore Grand Prix", raceName: "Singapore Grand Prix", round: 18 },
  { key: "usa", label: "Round 19 · United States Grand Prix", raceName: "United States Grand Prix", round: 19 },
  { key: "mexico-city", label: "Round 20 · Mexico City Grand Prix", raceName: "Mexico City Grand Prix", round: 20 },
  { key: "sao-paulo", label: "Round 21 · Sao Paulo Grand Prix", raceName: "Sao Paulo Grand Prix", round: 21 },
  { key: "las-vegas", label: "Round 22 · Las Vegas Grand Prix", raceName: "Las Vegas Grand Prix", round: 22 },
  { key: "qatar", label: "Round 23 · Qatar Grand Prix", raceName: "Qatar Grand Prix", round: 23 },
  { key: "abu-dhabi", label: "Round 24 · Abu Dhabi Grand Prix", raceName: "Abu Dhabi Grand Prix", round: 24 },
];

function normalize(value?: string) {
  return (value ?? "").trim().toLowerCase();
}

export function resolveRaceHeroTheme(raceName?: string): RaceHeroTheme {
  const normalized = normalize(raceName);
  if (!normalized) return DEFAULT_THEME;

  return (
    THEMES.find((theme) => theme.aliases.some((alias) => normalized.includes(alias))) ??
    DEFAULT_THEME
  );
}

export function buildCircuitAssetUrl(theme: RaceHeroTheme) {
  if (!theme.circuitId || !theme.layoutId) return null;
  return `https://raw.githubusercontent.com/julesr0y/f1-circuits-svg/main/circuits/${theme.svgStyle}/${theme.layoutId}.svg`;
}
